name: Add advinst_update.json

on:
  push:
    tags:
      - '*'

jobs: 
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Create json
        env:
          VERSION: ${{  github.ref_name }}
        run: |
          touch advinst_update.json
          echo '{ "RegistryKey":"HKUD\\Software\\co-IT.eu GmbH\\PDFDecrypter\\Version", "Version": "$VERSION" }' >> advinst_update.json
          readlink -e advinst_update.json
          cat advinst_update.json
      - name: Add json to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/PDFDecrypter/PDFDecrypter/advinst_update.json
          tag: ${{ github.ref }}
          overwrite: true
