name: Build Advanced Installer Project (.AIP)

on:
  push:
    tags:
      - '*'
jobs:
  advinst-aip-build-demo:
    runs-on: windows-latest
    name: Build Aip Demo
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # SDK Version to use.
      - run: dotnet restore --use-current-runtime PDFDecrypter/coIT.Tools.PDFDecrypter.csproj
      - run: dotnet build --configuration Release PDFDecrypter/coIT.Tools.PDFDecrypter.csproj
      - name: Copy Release to AIP build
        run: |
          mkdir D:\a\PDFDecrypter\source\repos\PDFDecrypter\PDFDecrypter\bin\Release\net7.0-windows\
          cp D:\a\PDFDecrypter\PDFDecrypter\PDFDecrypter\bin\Release\net7.0-windows\*.* D:\a\PDFDecrypter\source\repos\PDFDecrypter\PDFDecrypter\bin\Release\net7.0-windows\
      - name: Build AIP
        uses: caphyon/advinst-github-action@v1.0
        with:
          advinst-version: '21.1'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
          aip-path: ${{ github.workspace }}\PDFDecrypter.aip
          aip-build-name: DefaultBuild
          aip-package-name: setup.msi
          aip-output-dir:  ${{ github.workspace }}\setup
          aip-commands: |
            SetVersion ${{  github.ref_name }}
      - name: Publish setup artifact
        uses: actions/upload-artifact@v2
        with:
          name: setup
          path: ${{ github.workspace }}\setup\setup.msi
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: D:\a\PDFDecrypter\PDFDecrypter\setup\setup.msi
          tag: ${{ github.ref }}
          overwrite: true
      - uses: eregon/publish-release@v1
        name: Release Draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
